# Generated by Django 3.2 on 2022-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegemodel',
            name='imgurl',
            field=models.CharField(max_length=50, null=True, verbose_name='画像url'),
        ),
        migrations.AlterField(
            model_name='vegemodel',
            name='latestdate',
            field=models.CharField(max_length=50, verbose_name='最終更新日'),
        ),
        migrations.AlterField(
            model_name='vegemodel',
            name='price',
            field=models.CharField(max_length=50, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='vegemodel',
            name='vegename',
            field=models.CharField(max_length=50, verbose_name='野菜名'),
        ),
    ]
