# Generated by Django 3.2 on 2022-05-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeapp', '0002_auto_20220501_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegemodel',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='単位'),
        ),
        migrations.AddField(
            model_name='vegemodel',
            name='weight',
            field=models.CharField(max_length=50, null=True, verbose_name='重さ'),
        ),
    ]
